In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
##removing the irevelant columns
data.drop(['RowNumber',	'CustomerId',	'Surname'],axis=1,inplace=True)

In [5]:
##performing label encodinf on the gender column
lab_encoder=LabelEncoder()
data['Gender']=lab_encoder.fit_transform(data['Gender'])

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit_transform(data[['Geography']]).toarray()

In [8]:
one_hot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoder_df=pd.DataFrame(geo_encoder,columns=one_hot_encoder.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
## combine the one hot encoded data to the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(lab_encoder,file)
with open('one_hot_encoder_.pkl','wb') as file:
    pickle.dump(one_hot_encoder,file)

In [13]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [14]:
##identifying the dependent and independent features
x=data.drop('Exited',axis=1)
y=data['Exited']

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.32, random_state=42)

In [16]:
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [17]:
x_train

array([[-1.47343871, -1.09866993, -0.84676579, ...,  0.99530514,
        -0.57123698, -0.57984081],
       [-1.16178801,  0.91019147,  0.01097402, ..., -1.00471701,
        -0.57123698,  1.72461127],
       [-0.28916603,  0.91019147,  1.5358448 , ...,  0.99530514,
        -0.57123698, -0.57984081],
       ...,
       [ 0.86394159, -1.09866993, -0.0843304 , ...,  0.99530514,
        -0.57123698, -0.57984081],
       [ 0.15753332,  0.91019147,  0.39219172, ...,  0.99530514,
        -0.57123698, -0.57984081],
       [ 0.46918403,  0.91019147,  1.1546271 , ..., -1.00471701,
         1.75058696, -0.57984081]], shape=(6800, 12))

In [18]:
data.isnull().sum()

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
dtype: int64

In [19]:
with open('scalar.pkl','wb')as file:
    pickle.dump(scalar,file)

In [20]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [22]:
##ann impleentation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [ ]:
(x_train.shape[1],)

(12,)

In [ ]:
##build our ann model
model=Sequential(
    [
        Dense(32,activation='relu',input_shape=(x_train.shape[1],))
    ]
)

c:\Users\zaid\churn_modelling\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 32)             │           416 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 416 (1.62 KB)

 Trainable params: 416 (1.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [ ]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%M%D-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
!pip install TensorBoard

Requirement already satisfied: TensorBoard in .\.venv\Lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in .\.venv\Lib\site-packages (from TensorBoard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\.venv\Lib\site-packages (from TensorBoard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in .\.venv\Lib\site-packages (from TensorBoard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\.venv\Lib\site-packages (from TensorBoard) (2.4.4)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from TensorBoard) (26.0)
Requirement already satisfied: pillow in .\.venv\Lib\site-packages (from TensorBoard) (12.1.1)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\.venv\Lib\site-packages (from TensorBoard) (7.34.1)
Requirement already satisfied: setuptools>=41.0.0 in .\.venv\Lib\site-packages (from TensorBoard) (82.0.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\.venv\Lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\.venv\Lib\site-packages (from TensorBoard) (3.1.7)
Requirement already satisfied: typing-extensions~=4.12 in .\.venv\Lib\site-packages (from grpcio>=1.48.2->TensorBoard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\.venv\Lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.3)

In [ ]:
import tensorflow
model=Sequential(
    [
        Dense(32,activation='relu',input_shape=(x_train.shape[1],)),
        Dense(1,activation='sigmoid')
    ]
)
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss='BinaryCrossentropy',metrics=['accuracy'])
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100

c:\Users\zaid\churn_modelling\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

213/213 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8165 - loss: 0.4220 - val_accuracy: 0.8553 - val_loss: 0.3590
Epoch 2/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8488 - loss: 0.3627 - val_accuracy: 0.8581 - val_loss: 0.3515
Epoch 3/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8534 - loss: 0.3534 - val_accuracy: 0.8550 - val_loss: 0.3552
Epoch 4/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8516 - loss: 0.3526 - val_accuracy: 0.8491 - val_loss: 0.3535
Epoch 5/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8560 - loss: 0.3502 - val_accuracy: 0.8641 - val_loss: 0.3419
Epoch 6/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8550 - loss: 0.3498 - val_accuracy: 0.8644 - val_loss: 0.3365
Epoch 7/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8557 - loss: 0.3470 - val_accuracy: 0.8634 - val_loss: 0.3374
Epoch 8/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8581 - loss: 0.3444 - val_accuracy: 0.8609 - val_loss: 0.3412
Epoch 9/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8560 - loss: 0.3427 - val_accuracy: 0.8653 - val_loss: 0.3368
Epoch 10/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8565 - loss: 0.3418 - val_accuracy: 0.8637 - val_loss: 0.3353
Epoch 11/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8541 - loss: 0.3445 - val_accuracy: 0.8650 - val_loss: 0.3359
Epoch 12/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8574 - loss: 0.3421 - val_accuracy: 0.8616 - val_loss: 0.3373
Epoch 13/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8585 - loss: 0.3408 - val_accuracy: 0.8647 - val_loss: 0.3385
Epoch 14/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8596 - loss: 0.3385 - val_accuracy: 0.8634 - val_loss: 0.3377
Epoch 15/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8579 - loss: 0.3400 - val_accuracy: 0.8641 - val_loss: 0.3393
Epoch 16/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8576 - loss: 0.3374 - val_accuracy: 0.8603 - val_loss: 0.3402
Epoch 17/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8566 - loss: 0.3366 - val_accuracy: 0.8637 - val_loss: 0.3411
Epoch 18/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8574 - loss: 0.3387 - val_accuracy: 0.8625 - val_loss: 0.3455
Epoch 19/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8587 - loss: 0.3357 - val_accuracy: 0.8641 - val_loss: 0.3377
Epoch 20/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3368 - val_accuracy: 0.8659 - val_loss: 0.3322
Epoch 21/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3345 - val_accuracy: 0.8628 - val_loss: 0.3427
Epoch 22/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3362 - val_accuracy: 0.8659 - val_loss: 0.3334
Epoch 23/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8609 - loss: 0.3326 - val_accuracy: 0.8594 - val_loss: 0.3405
Epoch 24/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8587 - loss: 0.3338 - val_accuracy: 0.8666 - val_loss: 0.3382
Epoch 25/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8637 - loss: 0.3322 - val_accuracy: 0.8634 - val_loss: 0.3334
Epoch 26/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8601 - loss: 0.3349 - val_accuracy: 0.8709 - val_loss: 0.3315
Epoch 27/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8599 - loss: 0.3314 - val_accuracy: 0.8666 - val_loss: 0.3307
Epoch 28/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8574 - loss: 0.3319 - val_accuracy: 0.8675 - val_loss: 0.3326
Epoch 29/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8628 - loss: 0.3303 - val_accuracy: 0.8641 - val_loss: 0.3351
Epoch 30/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8601 - loss: 0.3314 - val_accuracy: 0.8675 - val_loss: 0.3320
Epoch 31/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8634 - loss: 0.3307 - val_accuracy: 0.8628 - val_loss: 0.3363
Epoch 32/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8600 - loss: 0.3324 - val_accuracy: 0.8625 - val_loss: 0.3366
Epoch 33/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8612 - loss: 0.3304 - val_accuracy: 0.8641 - val_loss: 0.3413
Epoch 34/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3302 - val_accuracy: 0.8612 - val_loss: 0.3341
Epoch 35/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8640 - loss: 0.3275 - val_accuracy: 0.8666 - val_loss: 0.3353
Epoch 36/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8612 - loss: 0.3304 - val_accuracy: 0.8641 - val_loss: 0.3348
Epoch 37/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8609 - loss: 0.3292 - val_accuracy: 0.8684 - val_loss: 0.3418

In [ ]:
model.save('model.keras')