In [60]:
import tensorflow as tf
from tensorflow.keras import models
import pickle
import keras
import pandas as pd
import numpy as np

In [61]:
with open('model.keras','rb') as file:
    model = keras.models.load_model('model.keras')

#load the label encoder pickle file
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

#load tje one hot encoder pickle file
with open('one_hot_encoder_.pkl','rb') as file:
    one_hot_enco=pickle.load(file)

#load the standadization pickle file
with open('scalar.pkl','rb') as file:
    scalar=pickle.load(file)

In [62]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [63]:
geo_encode=one_hot_enco.transform([[input_data['Geography']]]).toarray()
geo_encoder_df=pd.DataFrame(geo_encode,columns=one_hot_enco.get_feature_names_out(['Geography']))
geo_encoder_df

c:\Users\zaid\churn_modelling\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [64]:
input_data=pd.DataFrame([input_data])

In [65]:
input_data['Gender']=label_encoder_gender.transform(input_data['Gender'])

In [66]:
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [67]:
input_data=pd.concat([input_data.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [68]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [69]:
input_scaled=scalar.transform(input_data)

In [70]:
prediction=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step

In [73]:
prediction_proba=prediction[0][0]

In [75]:
prediction_proba

np.float32(0.021844983)

In [74]:
if prediction_proba>0.5:
    print('the customer is likely to churn')
else:
    print('the customer is not likely to churn')

the customer is not likely to churn